"""
post-weekly-social.py — config-driven social post fire (generic, brand-agnostic)

Reads:
  - config/brand.json — forbidden phrases, validated stats, palette
  - config/channels.json — CMS, Make.com webhook + API, schedule, notifications
  - outputs/social/pending/weekly-*.json — packet generated by weekly-social-packet skill

Output:
  - PNG render of clickbait_svg
  - Upload to CMS /files endpoint
  - Fire 2+ webhooks to Make.com (one per enabled channel)
  - Verify Make.com execution status (Fix 1)
  - Telegram alert success or failure

Generic — no hardcoded brand. Forks for other brands just edit config/.
Built by Ruby for the Content Engine plugin.
"""
from __future__ import annotations
import argparse
import importlib.util
import json
import sys
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path


# ============================================================
# Config loading
# ============================================================

def find_plugin_root() -> Path:
    here = Path(__file__).resolve()
    for ancestor in [here.parent, *here.parents]:
        if (ancestor / ".claude-plugin" / "plugin.json").exists():
            return ancestor
    return here.parent.parent


def load_brand_config(plugin_root: Path, profile: str = None) -> dict:
    """Load brand config. profile lets you use examples/<brand>/config/brand.json."""
    if profile:
        p = plugin_root / "examples" / profile / "config" / "brand.json"
    else:
        p = plugin_root / "config" / "brand.json"
    if not p.exists():
        sys.exit(f"Brand config not found: {p}\nFill from config/brand.template.json first.")
    return json.loads(p.read_text(encoding="utf-8"))


def load_channels_config(plugin_root: Path, profile: str = None) -> dict:
    if profile:
        p = plugin_root / "examples" / profile / "config" / "channels.json"
    else:
        p = plugin_root / "config" / "channels.json"
    if not p.exists():
        sys.exit(f"Channels config not found: {p}\nFill from config/channels.template.json first.")
    return json.loads(p.read_text(encoding="utf-8"))


def read_secret(plugin_root: Path, profile: str, filename: str) -> str:
    """Read gitignored secret file (e.g., .cms-token, .make-webhook-url)."""
    if profile:
        p = plugin_root / "examples" / profile / "config" / filename
    else:
        p = plugin_root / "config" / filename
    if not p.exists():
        sys.exit(f"Secret file missing: {p}")
    return p.read_text(encoding="utf-8").strip()


# ============================================================
# Brand validators (read forbidden lists from brand.json)
# ============================================================

def extract_stat_claims_from_svg(svg: str) -> list:
    import re
    text_blocks = re.findall(r"<text[^>]*>(.*?)</text>", svg, flags=re.DOTALL | re.IGNORECASE)
    blob = re.sub(r"<[^>]+>", " ", "\n".join(text_blocks))
    claims = set()
    for m in re.findall(r"\b\d+(?:\.\d+)?%", blob):
        claims.add(m)
    for m in re.findall(r"\b\d+(?:\.\d+)?x\b", blob):
        claims.add(m)
    for m in re.findall(r"\$\d+(?:\.\d+)?[KMB]?\b", blob):
        claims.add(m)
    return sorted(claims)


def validate_post_text(text: str, brand: dict, label: str = "post") -> tuple:
    """Validate post body against brand voice rules from config."""
    errors = []
    if not text:
        return False, [f"{label}: empty text"]
    tl = text.lower()

    voice = brand.get("voice", {})
    forbidden = voice.get("forbidden_phrases", {})
    chars = voice.get("forbidden_chars", {})

    if chars.get("em_dash") and "—" in text:
        errors.append(f"{label}: contains em dash (—)")
    if chars.get("en_dash") and "–" in text:
        errors.append(f"{label}: contains en dash (–)")
    if chars.get("emoji"):
        for ch in text:
            cp = ord(ch)
            if (0x1F300 <= cp <= 0x1FAFF) or (0x2600 <= cp <= 0x27BF):
                errors.append(f"{label}: contains emoji U+{cp:04X}")
                break

    for tell in forbidden.get("ai_tells", []):
        if tell.lower() in tl:
            errors.append(f"{label}: contains AI tell '{tell}'")

    approved_only = set(p.lower() for p in voice.get("required_phrasings", {}).get("approved_only_phrasings", []))
    for claim in forbidden.get("overclaims", []):
        if claim.lower() in tl and not any(a in tl for a in approved_only):
            errors.append(f"{label}: contains overclaim '{claim}'")

    return len(errors) == 0, errors


def validate_clickbait_svg(svg: str, brand: dict) -> tuple:
    """Validate SVG against brand palette + forbidden colors + required wordmark."""
    errors = []
    if not svg or not isinstance(svg, str):
        return False, ["SVG empty"]
    s = svg.strip()
    if not s.startswith("<svg") or not s.rstrip().endswith("</svg>"):
        errors.append("SVG must start with <svg and end with </svg>")
    sl = s.lower()

    palette = brand.get("palette", {})
    forbidden_colors = palette.get("_forbidden_colors", {})
    company = brand.get("company", {})

    # Brand wordmark required
    domain = company.get("domain", "")
    tagline = company.get("tagline", "")
    if domain and domain.lower() not in sl:
        errors.append(f"Missing wordmark '{domain}'")
    if tagline and tagline.lower() not in sl:
        errors.append(f"Missing tagline '{tagline}'")

    # Forbidden hex colors
    for hex_color in forbidden_colors.get("hex", []):
        if hex_color.lower() in sl:
            errors.append(f"Contains forbidden hex {hex_color}")
    for rgba_prefix in forbidden_colors.get("rgba_prefixes", []):
        if rgba_prefix.lower() in sl:
            errors.append(f"Contains forbidden rgba '{rgba_prefix}...'")

    return len(errors) == 0, errors


def validate_stats_trace(svg: str, source_text: str, source_label: str) -> tuple:
    """Every numeric claim in SVG must appear in source_text (or alt form)."""
    import re
    if not source_text or not source_text.strip():
        return True, [f"WARNING: {source_label} empty, skipping stat-trace"]
    claims = extract_stat_claims_from_svg(svg)
    if not claims:
        return True, []
    src_lower = source_text.lower()
    missing = []
    for c in claims:
        if c.lower() in src_lower:
            continue
        num_match = re.match(r"(\d+(?:\.\d+)?)", c)
        if num_match:
            num = num_match.group(1)
            alts = []
            if c.endswith("%"):
                alts = [f"{num} percent"]
            elif c.lower().endswith("x"):
                alts = [f"{num}x", f"{num} times", f"{num}-fold"]
            elif c.startswith("$"):
                alts = [c.lower(), num]
            if any(a in src_lower for a in alts):
                continue
        missing.append(c)
    if missing:
        return False, [f"SVG stat '{m}' not in {source_label}" for m in missing]
    return True, []


# ============================================================
# CMS upload + webhook fire
# ============================================================

def render_svg_to_png(svg: str, width: int = 1080) -> bytes:
    """Render SVG to PNG using cairosvg (preferred) or Playwright (fallback)."""
    try:
        import cairosvg
        return cairosvg.svg2png(bytestring=svg.encode("utf-8"), output_width=width)
    except ImportError:
        pass
    # Fallback: Playwright
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch()
            page = browser.new_page(viewport={"width": width, "height": width})
            page.set_content(f'<html><body style="margin:0">{svg}</body></html>')
            time.sleep(2.5)
            png = page.screenshot(omit_background=True)
            browser.close()
            return png
    except Exception as e:
        sys.exit(f"SVG render failed: {e}")


def upload_to_cms(channels: dict, plugin_root: Path, profile: str, png_bytes: bytes, filename: str) -> str:
    """Upload PNG to CMS /files endpoint. Returns asset UUID."""
    import requests
    cms = channels["cms"]
    token = read_secret(plugin_root, profile, cms["token_file"])
    base_url = cms["base_url"].rstrip("/")

    if cms["provider"] == "directus":
        files = {
            "file": (filename, png_bytes, "image/png"),
            "title": (None, filename.replace(".png", "").replace("-", " ").title()),
        }
        if cms.get("files_folder_uuid"):
            files["folder"] = (None, cms["files_folder_uuid"])
        r = requests.post(
            f"{base_url}/files",
            headers={"Authorization": f"Bearer {token}"},
            files=files,
            timeout=60,
        )
        if r.status_code in (200, 201):
            return r.json()["data"]["id"]
        sys.exit(f"CMS upload failed: HTTP {r.status_code} {r.text[:300]}")
    else:
        sys.exit(f"CMS provider not supported: {cms['provider']}")


def post_to_webhook(webhook_url: str, payload: dict) -> tuple:
    import requests
    r = requests.post(
        webhook_url,
        headers={"Content-Type": "application/json"},
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        timeout=30,
    )
    return r.status_code, r.text


def verify_make_executions(channels: dict, plugin_root: Path, profile: str, fire_time_utc: datetime, wait_seconds: int = 90) -> dict:
    """Query Make.com API to verify executions succeeded after webhook fire."""
    import requests
    social = channels["social"]
    api_token_file = social.get("make_api_token_file")
    if not api_token_file:
        return {"ok": False, "reason": "make_api_token_file not configured", "skip": True}
    try:
        api_token = read_secret(plugin_root, profile, api_token_file)
    except SystemExit:
        return {"ok": False, "reason": "Make API token file not present", "skip": True}
    scenario_id = social.get("make_scenario_id", "").strip()
    base_url = social.get("make_base_url", "https://eu1.make.com").rstrip("/")
    if not scenario_id or scenario_id.startswith("REPLACE"):
        return {"ok": False, "reason": "make_scenario_id not configured", "skip": True}

    print(f"\nWaiting {wait_seconds}s for Make.com to process webhooks...")
    time.sleep(wait_seconds)

    url = f"{base_url}/api/v2/scenarios/{scenario_id}/logs?limit=10"
    try:
        r = requests.get(url, headers={"Authorization": f"Token {api_token}"}, timeout=30)
        if r.status_code != 200:
            return {"ok": False, "reason": f"Make API HTTP {r.status_code}: {r.text[:200]}", "executions": []}
        all_logs = r.json().get("scenarioLogs", []) or r.json().get("data", [])
        window_start = (fire_time_utc - timedelta(minutes=1)).replace(tzinfo=timezone.utc)
        window_end = (fire_time_utc + timedelta(minutes=5)).replace(tzinfo=timezone.utc)
        recent = []
        for log in all_logs:
            started = log.get("startedAt") or log.get("started_at") or log.get("timestamp")
            if not started:
                continue
            try:
                t = datetime.fromisoformat(started.replace("Z", "+00:00"))
                if window_start <= t <= window_end:
                    recent.append(log)
            except Exception:
                pass
        if not recent:
            return {"ok": False, "reason": "No executions in 5-min window (scenario may be Inactive)"}
        errors = [e for e in recent if str(e.get("status", "")).lower() in ("error", "failed", "3")]
        if errors:
            err = errors[0].get("error") or errors[0].get("message") or "unknown"
            return {"ok": False, "reason": f"{len(errors)}/{len(recent)} executions failed", "details": err}
        return {"ok": True, "reason": f"{len(recent)} executions completed"}
    except Exception as e:
        return {"ok": False, "reason": f"API call failed: {e}"}


def notify_telegram(channels: dict, plugin_root: Path, profile: str, message: str) -> bool:
    """Send Telegram message via bot API. Returns True on success."""
    import urllib.parse, urllib.request
    notif_file = channels.get("notifications", {}).get("telegram", {}).get("config_file")
    if not notif_file:
        return False
    if profile:
        p = plugin_root / "examples" / profile / "config" / notif_file
    else:
        p = plugin_root / "config" / notif_file
    if not p.exists():
        return False
    try:
        cfg = json.loads(p.read_text(encoding="utf-8"))
        bot_token = cfg.get("bot_token", "").strip()
        chat_id = cfg.get("chat_id", "").strip()
        if not bot_token or not chat_id:
            return False
        url = (
            f"https://api.telegram.org/bot{bot_token}/sendMessage"
            f"?chat_id={urllib.parse.quote(str(chat_id))}"
            f"&text={urllib.parse.quote(message)}"
        )
        req = urllib.request.Request(url, headers={"User-Agent": "ContentEngineByRuby"})
        urllib.request.urlopen(req, timeout=15)
        return True
    except Exception as e:
        print(f"  Telegram notify failed: {e}")
        return False


# ============================================================
# Main
# ============================================================

def main():
    ap = argparse.ArgumentParser(description="Fire weekly social packet via Make.com webhook. Config-driven, brand-agnostic.")
    ap.add_argument("--file", help="Specific JSON file. Default: newest in outputs/social/pending/")
    ap.add_argument("--profile", help="Use examples/<profile>/config/ instead of config/. E.g. --profile luna-base")
    ap.add_argument("--dry-run", action="store_true", help="Preview payloads, skip upload + fire")
    ap.add_argument("--no-archive", action="store_true", help="Don't move JSON to processed/ after fire")
    args = ap.parse_args()

    plugin_root = find_plugin_root()
    print(f"Plugin root: {plugin_root}")
    brand = load_brand_config(plugin_root, args.profile)
    channels = load_channels_config(plugin_root, args.profile)
    print(f"Brand: {brand['company']['name']}")

    # Find pending JSON
    if args.file:
        json_path = Path(args.file)
        if not json_path.is_absolute():
            json_path = plugin_root / json_path
    else:
        if args.profile:
            pending_dir = plugin_root / "examples" / args.profile / "outputs" / "social" / "pending"
        else:
            pending_dir = plugin_root / "outputs" / "social" / "pending"
        candidates = sorted(pending_dir.glob("weekly-*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
        if not candidates:
            sys.exit(f"No pending JSON in {pending_dir}")
        json_path = candidates[0]
    print(f"Packet: {json_path}")

    packet = json.loads(json_path.read_text(encoding="utf-8"))
    post_type = packet.get("post_type", "blog_driver")
    print(f"Post type: {post_type}")

    # Validators
    li_ok, li_errs = validate_post_text(packet["linkedin_post"], brand, "LinkedIn")
    fb_ok, fb_errs = validate_post_text(packet["facebook_post"], brand, "Facebook")
    if not (li_ok and fb_ok):
        for e in li_errs + fb_errs:
            print(f"  - {e}")
        sys.exit("Post text validation FAILED. Fix packet and re-run.")

    # Image provider: 'canva' (per-channel PNGs generated by the skill) or 'svg' (legacy render).
    img_provider = packet.get("image_provider") or brand.get("format", {}).get("images", {}).get("provider", "svg")
    canva_mode = img_provider == "canva" and bool(packet.get("image_linkedin_path") or packet.get("image_facebook_path"))

    svg = packet.get("clickbait_svg")
    if not canva_mode:
        # Legacy SVG path: validate the SVG + stat-trace.
        if not svg:
            sys.exit("No clickbait_svg in packet and image provider is not canva.")
        sv_ok, sv_errs = validate_clickbait_svg(svg, brand)
        if not sv_ok:
            for e in sv_errs:
                print(f"  - {e}")
            sys.exit("SVG validation FAILED.")
        if post_type == "blog_driver":
            stat_source = packet.get("blog_html", "")
            stat_label = "blog_html"
        else:
            stats_blob = json.dumps(brand.get("validated_stats", {}).get("entries", []), ensure_ascii=False)
            stat_source = stats_blob
            stat_label = "brand.validated_stats"
        st_ok, st_errs = validate_stats_trace(svg, stat_source, stat_label)
        if not st_ok:
            for e in st_errs:
                print(f"  - {e}")
            sys.exit("Stat-trace FAILED.")

    print(f"All validators PASS. Image provider: {'canva' if canva_mode else 'svg'}")

    if args.dry_run:
        print("\n[DRY RUN] Skipping CMS upload + webhook fire.")
        return

    cms = channels["cms"]
    image_basename = packet.get("blog_slug") or packet.get("feature_specific", "social-card").lower().replace(" ", "-")[:60]

    def channel_image_url(channel_field, cache):
        """Hosted image URL for this channel. Canva: per-channel PNG; SVG: one shared render."""
        if canva_mode:
            rel = packet.get("image_linkedin_path") if "linkedin" in channel_field else packet.get("image_facebook_path")
            rel = rel or packet.get("image_linkedin_path") or packet.get("image_facebook_path")
            png_file = json_path.parent / Path(rel).name
            if not png_file.exists():
                sys.exit(f"Canva image not found: {png_file}")
            key = png_file.name
            if key not in cache:
                data = png_file.read_bytes()
                uuid = upload_to_cms(channels, plugin_root, args.profile, data, key)
                cache[key] = cms["image_url_pattern"].format(base_url=cms["base_url"].rstrip("/"), uuid=uuid)
            return cache[key]
        if "svg_render" not in cache:
            social_size = brand.get("svg_figure", {}).get("social_card_size_px", 1080)
            data = render_svg_to_png(svg, width=social_size)
            uuid = upload_to_cms(channels, plugin_root, args.profile, data, f"{image_basename}-weekly-social.png")
            cache["svg_render"] = cms["image_url_pattern"].format(base_url=cms["base_url"].rstrip("/"), uuid=uuid)
        return cache["svg_render"]

    webhook_url = read_secret(plugin_root, args.profile, channels["social"]["make_webhook_url_file"])
    fire_time_utc = datetime.utcnow()
    all_ok = True
    upload_cache = {}
    for ch_name, ch_cfg in channels["social"]["channels"].items():
        if not ch_cfg.get("enabled"):
            continue
        channel_field = ch_cfg["channel_field_value"]
        image_url = channel_image_url(channel_field, upload_cache)
        payload = {
            "blog_title": packet.get("blog_title") or packet.get("feature_specific", ""),
            "blog_url": packet.get("blog_url") or brand["company"]["url"],
            "post_text": packet["linkedin_post" if "linkedin" in channel_field else "facebook_post"],
            "post_visibility": ch_cfg.get("post_visibility", "PUBLIC"),
            "image_url": image_url,
            "image_title": packet.get("image_title", ""),
            "image_alt": packet.get("image_alt", ""),
            "channel": channel_field,
            "post_type": post_type,
            "schedule_iso": "",
        }
        status, body = post_to_webhook(webhook_url, payload)
        print(f"  {ch_name}: image {image_url} -> HTTP {status}")
        if not (200 <= status < 300):
            all_ok = False

    # Verify Make.com executions
    if all_ok:
        result = verify_make_executions(channels, plugin_root, args.profile, fire_time_utc)
        if result.get("skip"):
            msg = (
                f"Social posts fired (verification skipped)\n"
                f"Brand: {brand['company']['name']}\n"
                f"Time: {fire_time_utc.strftime('%Y-%m-%d %H:%M UTC')}\n"
                f"Check feeds in 5 min."
            )
        elif result["ok"]:
            print(f"\nVerification PASS: {result['reason']}")
            feed_links = [c.get("feed_url", "") for c in channels["social"]["channels"].values() if c.get("enabled") and c.get("feed_url")]
            msg = (
                f"Social posts: POSTED\n"
                f"Brand: {brand['company']['name']}\n"
                f"Time: {fire_time_utc.strftime('%Y-%m-%d %H:%M UTC')}\n"
                f"Verified: {result['reason']}\n"
                + "\n".join(feed_links)
            )
        else:
            print(f"\nVerification FAIL: {result['reason']}")
            msg = (
                f"SOCIAL POSTS FAILED\n"
                f"Brand: {brand['company']['name']}\n"
                f"Time: {fire_time_utc.strftime('%Y-%m-%d %H:%M UTC')}\n"
                f"Reason: {result['reason']}\n"
                f"Details: {str(result.get('details',''))[:200]}\n"
                f"Action: check Make.com History, fix, re-fire."
            )
        notify_telegram(channels, plugin_root, args.profile, msg)

    if all_ok and not args.no_archive:
        processed_dir = json_path.parent.parent / "processed"
        processed_dir.mkdir(parents=True, exist_ok=True)
        target = processed_dir / json_path.name
        json_path.rename(target)
        print(f"Archived: {target.name}")

    sys.exit(0 if all_ok else 1)


if __name__ == "__main__":
    main()
