"""
publish-blog.py - config-driven blog HTML publisher (generic, brand-agnostic)

Reads:
  - config/brand.json - palette, typography, voice rules, validated stats
  - config/channels.json - CMS provider, base_url, token_file, fields mapping
  - outputs/blogs/draft-YYYY-MM-DD-slot-X-*.html - draft generated by blog skill

Output:
  - Render best figure (highest visual richness score) as PNG thumbnail
  - Validate HTML body against brand rules (forbidden chars, palette, voice)
  - Inline CSS to be CMS-safe
  - POST thumbnail to CMS /files
  - POST blog body to CMS /items/<collection> with field mapping from channels.json
  - Telegram alert success or failure
  - Move draft to outputs/blogs/published-YYYYMMDD-<slug>.html

Generic - no hardcoded brand. Forks for other brands just edit config/.
Built by Ruby for the Content Engine plugin.

Usage:
  python scripts/publish-blog.py --slot A
  python scripts/publish-blog.py --slot B --profile luna-base
  python scripts/publish-blog.py --draft outputs/blogs/draft-2026-06-01-slot-A-foo.html
"""
from __future__ import annotations
import argparse
import importlib.util
import json
import re
import socket
import sys
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path


# ============================================================
# Config loading (same pattern as post-weekly-social.py)
# ============================================================

def find_plugin_root() -> Path:
    here = Path(__file__).resolve()
    for ancestor in [here.parent, *here.parents]:
        if (ancestor / ".claude-plugin" / "plugin.json").exists():
            return ancestor
    return here.parent.parent


def load_brand_config(plugin_root: Path, profile: str = None) -> dict:
    if profile:
        p = plugin_root / "examples" / profile / "config" / "brand.json"
    else:
        p = plugin_root / "config" / "brand.json"
    if not p.exists():
        sys.exit(f"Brand config not found: {p}\nFill from config/brand.template.json first.")
    return json.loads(p.read_text(encoding="utf-8"))


def load_channels_config(plugin_root: Path, profile: str = None) -> dict:
    if profile:
        p = plugin_root / "examples" / profile / "config" / "channels.json"
    else:
        p = plugin_root / "config" / "channels.json"
    if not p.exists():
        sys.exit(f"Channels config not found: {p}\nFill from config/channels.template.json first.")
    return json.loads(p.read_text(encoding="utf-8"))


def read_secret(plugin_root: Path, profile: str, filename: str) -> str:
    if profile:
        p = plugin_root / "examples" / profile / "config" / filename
    else:
        p = plugin_root / "config" / filename
    if not p.exists():
        sys.exit(f"Secret file missing: {p}")
    return p.read_text(encoding="utf-8").strip()


# ============================================================
# Output paths
# ============================================================

def outputs_root(plugin_root: Path, profile: str = None) -> Path:
    """Where drafts live. Default plugin_root/outputs/, profile overrides to examples/<profile>/outputs/."""
    if profile:
        return plugin_root / "examples" / profile / "outputs"
    return plugin_root / "outputs"


def drafts_dir(plugin_root: Path, profile: str = None) -> Path:
    d = outputs_root(plugin_root, profile) / "blogs"
    d.mkdir(parents=True, exist_ok=True)
    return d


# ============================================================
# Network + DNS preflight (lessons from May 2 incident)
# ============================================================

def dns_preflight(host: str, retries: int = 3, wait_seconds: int = 30) -> bool:
    """Resolve host with retries. Returns True if resolves, False if all retries fail."""
    last_err = None
    for attempt in range(retries + 1):
        try:
            socket.gethostbyname(host)
            return True
        except socket.gaierror as e:
            last_err = e
            if attempt < retries:
                sleep_for = wait_seconds * (2 ** attempt) if attempt > 0 else wait_seconds
                print(f"[dns] resolve {host} failed (attempt {attempt+1}): {e}. sleeping {sleep_for}s", flush=True)
                time.sleep(sleep_for)
    print(f"[dns] ABORT - {host} unreachable after {retries+1} attempts. Last error: {last_err}", flush=True)
    return False


def requests_with_retry(method: str, url: str, retries: int = 2, **kwargs):
    """Wrap requests with ConnectionError/Timeout retry."""
    import requests
    last_err = None
    for attempt in range(retries + 1):
        try:
            return requests.request(method, url, **kwargs)
        except (requests.ConnectionError, requests.Timeout) as e:
            last_err = e
            if attempt < retries:
                sleep_for = 30 * (2 ** attempt)
                print(f"[net] {method} {url} failed (attempt {attempt+1}): {e}. sleeping {sleep_for}s", flush=True)
                time.sleep(sleep_for)
    raise last_err


# ============================================================
# Draft discovery
# ============================================================

def find_draft_for_slot(drafts: Path, slot: str, target_date: str = None) -> Path:
    """Find draft for slot. target_date YYYY-MM-DD, defaults to today."""
    if target_date is None:
        target_date = datetime.now().strftime("%Y-%m-%d")
    pattern = f"draft-{target_date}-slot-{slot}-*.html"
    matches = sorted(drafts.glob(pattern))
    if matches:
        return matches[-1]
    # Fallback: oldest queued draft for this slot, any date
    fallback = sorted(drafts.glob(f"draft-*-slot-{slot}-*.html"))
    if fallback:
        print(f"[draft] no draft for {target_date} slot {slot}, falling back to oldest: {fallback[0].name}", flush=True)
        return fallback[0]
    sys.exit(f"No draft found for slot {slot} in {drafts}")


def extract_slug_from_draft(draft_path: Path) -> str:
    """draft-2026-06-01-slot-A-my-cool-blog.html -> my-cool-blog"""
    name = draft_path.stem
    m = re.match(r"draft-\d{4}-\d{2}-\d{2}-slot-[A-Z]-(.+)", name)
    return m.group(1) if m else name


# ============================================================
# HTML validators
# ============================================================

def validate_body_html(html: str, brand: dict) -> tuple:
    """Validate HTML body against brand rules. Returns (ok, errors)."""
    errors = []
    chars = brand.get("voice", {}).get("forbidden_chars", {})
    if chars.get("em_dash") and "—" in html:
        errors.append("contains em dash U+2014")
    if chars.get("en_dash") and "–" in html:
        errors.append("contains en dash U+2013")
    if chars.get("emoji"):
        for ch in html:
            cp = ord(ch)
            if (0x1F300 <= cp <= 0x1FAFF) or (0x2600 <= cp <= 0x27BF):
                errors.append(f"contains emoji U+{cp:04X}")
                break

    # Forbidden palette colors
    palette = brand.get("palette", {})
    forbidden = palette.get("_forbidden_colors", {})
    for hex_color in forbidden.get("hex", []):
        if hex_color.lower() in html.lower():
            errors.append(f"contains forbidden color {hex_color}")
    for rgba_prefix in forbidden.get("rgba_prefixes", []):
        if rgba_prefix.lower() in html.lower():
            errors.append(f"contains forbidden rgba prefix {rgba_prefix}")

    # Forbidden phrases (article body voice rules apply)
    voice = brand.get("voice", {})
    forbidden_phrases = voice.get("forbidden_phrases", {})
    text_only = re.sub(r"<[^>]+>", " ", html).lower()
    for tell in forbidden_phrases.get("ai_tells", []):
        if tell.lower() in text_only:
            errors.append(f"contains AI tell '{tell}'")

    # Single H1 rule
    h1_count = len(re.findall(r"<h1[\s>]", html, flags=re.IGNORECASE))
    if h1_count != 1:
        errors.append(f"expected 1 H1, found {h1_count}")

    return (len(errors) == 0), errors


def extract_meta(html: str, name: str) -> str:
    """Pull <meta name|property="X" content="Y"> from HTML head."""
    patterns = [
        rf'<meta\s+name=["\']{re.escape(name)}["\']\s+content=["\']([^"\']*)["\']',
        rf'<meta\s+property=["\']{re.escape(name)}["\']\s+content=["\']([^"\']*)["\']',
        rf'<meta\s+content=["\']([^"\']*)["\']\s+name=["\']{re.escape(name)}["\']',
    ]
    for p in patterns:
        m = re.search(p, html, flags=re.IGNORECASE)
        if m:
            return m.group(1).strip()
    return ""


def extract_title(html: str) -> str:
    m = re.search(r"<title>([^<]*)</title>", html, flags=re.IGNORECASE)
    return m.group(1).strip() if m else ""


def extract_h1(html: str) -> str:
    m = re.search(r"<h1[^>]*>([\s\S]*?)</h1>", html, flags=re.IGNORECASE)
    return re.sub(r"<[^>]+>", " ", m.group(1)).strip() if m else ""


def extract_first_paragraph(html: str) -> str:
    m = re.search(r"<p[^>]*>([\s\S]*?)</p>", html, flags=re.IGNORECASE)
    if not m:
        return ""
    return re.sub(r"<[^>]+>", " ", m.group(1)).strip()


# ============================================================
# Figure selection + rendering (the "best figure as thumbnail" rule)
# ============================================================

def extract_figures(html: str) -> list:
    """Extract <svg> blocks from article body."""
    return re.findall(r"<svg[\s\S]*?</svg>", html, flags=re.IGNORECASE)


def score_figure_richness(svg: str) -> float:
    """Higher = more visually rich. The pipeline picks max for thumbnail.

    Rewards: animations, gradients, paths, filters, curves
    Penalizes: heavy rect grids (looks like generic 4-card dashboard)
    """
    score = 0.0
    score += len(re.findall(r"<animate[\s>]", svg)) * 5
    score += len(re.findall(r"<animateMotion[\s>]", svg)) * 8
    score += len(re.findall(r"<animateTransform[\s>]", svg)) * 5
    score += len(re.findall(r"<linearGradient[\s>]", svg)) * 3
    score += len(re.findall(r"<radialGradient[\s>]", svg)) * 4
    score += len(re.findall(r"<filter[\s>]", svg)) * 4
    score += len(re.findall(r"<path[\s>]", svg)) * 2
    score += len(re.findall(r"\bd=[\"\'][^\"\']*[CcQqAa]", svg)) * 1.5  # curves

    rect_count = len(re.findall(r"<rect[\s>]", svg))
    if rect_count > 4:
        # Penalty for rect-grid-heavy figures (generic dashboards)
        score -= (rect_count - 4) * 3
    return score


def pick_best_figure(figures: list) -> tuple:
    """Returns (index, svg, score) for best figure or (-1, None, 0) if none."""
    if not figures:
        return (-1, None, 0)
    best_i, best_score = 0, score_figure_richness(figures[0])
    for i, svg in enumerate(figures[1:], start=1):
        s = score_figure_richness(svg)
        if s > best_score:
            best_i, best_score = i, s
    return (best_i, figures[best_i], best_score)


def render_svg_to_png(svg: str, width: int = 1200) -> bytes:
    """Render SVG to PNG. cairosvg primary, Playwright fallback."""
    try:
        if importlib.util.find_spec("cairosvg"):
            import cairosvg
            return cairosvg.svg2png(bytestring=svg.encode("utf-8"), output_width=width)
    except Exception as e:
        print(f"[render] cairosvg failed: {e}, trying Playwright", flush=True)
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch()
            page = browser.new_page(viewport={"width": width, "height": int(width * 0.625)})
            page.set_content(f"<html><body style='margin:0'>{svg}</body></html>")
            page.wait_for_timeout(2500)  # let SMIL settle
            png = page.screenshot(omit_background=False)
            browser.close()
            return png
    except Exception as e:
        sys.exit(f"[render] all renderers failed: {e}")


# ============================================================
# CSS inlining (CMS-safe)
# ============================================================

def inline_css_into_body(html: str) -> str:
    """Pull <style> blocks from head and inline their rules into matching body elements.

    Pure stdlib, conservative: matches simple selectors only (tag, .class, #id, combinations).
    Preserves inline style attrs already present.
    """
    # Find all <style> blocks in head
    styles = re.findall(r"<style[^>]*>([\s\S]*?)</style>", html, flags=re.IGNORECASE)
    if not styles:
        # Already inline or no styles
        body_match = re.search(r"<body[^>]*>([\s\S]*?)</body>", html, flags=re.IGNORECASE)
        return body_match.group(1) if body_match else html

    css_text = "\n".join(styles)
    # Strip CSS comments
    css_text = re.sub(r"/\*[\s\S]*?\*/", "", css_text)

    # Parse rules (selector { decls })
    rules = []
    for m in re.finditer(r"([^{}]+)\{([^{}]+)\}", css_text):
        selector = m.group(1).strip()
        decls = m.group(2).strip().rstrip(";")
        if selector and decls:
            rules.append((selector, decls))

    body_match = re.search(r"<body[^>]*>([\s\S]*?)</body>", html, flags=re.IGNORECASE)
    body = body_match.group(1) if body_match else html

    # Apply simple-selector rules to tags by matching tag + class + id only
    # This is a conservative pass; not a full CSS engine.
    for selector, decls in rules:
        # Split compound selectors by comma
        for sel in [s.strip() for s in selector.split(",")]:
            if not sel:
                continue
            # Only single-element selectors: tag, .class, #id, tag.class
            simple = re.match(r"^([a-zA-Z]+)?(\.[\w-]+)?(\#[\w-]+)?$", sel)
            if not simple:
                continue
            tag, cls, id_ = simple.groups()
            tag = tag or r"[a-zA-Z][\w]*"
            attr_filter = ""
            if cls:
                cls_name = cls[1:]
                attr_filter = rf'[^>]*class=["\'][^"\']*\b{re.escape(cls_name)}\b[^"\']*["\']'
            elif id_:
                id_name = id_[1:]
                attr_filter = rf'[^>]*id=["\']{re.escape(id_name)}["\']'
            # Append decls to existing style="" or add new
            pattern = rf'<({tag}){attr_filter}([^>]*?)(\s*/?>)'

            def inject(mt):
                opentag = mt.group(0)
                if 'style="' in opentag or "style='" in opentag:
                    return re.sub(
                        r'style=(["\'])([^"\']*)\1',
                        lambda sm: f'style={sm.group(1)}{sm.group(2).rstrip(";")};{decls}{sm.group(1)}',
                        opentag, count=1,
                    )
                return opentag[:-len(mt.group(3))] + f' style="{decls}"' + mt.group(3)

            try:
                body = re.sub(pattern, inject, body)
            except re.error:
                continue
    return body


# ============================================================
# CMS upload (Directus by default; extensible by provider)
# ============================================================

def upload_thumbnail(channels: dict, plugin_root: Path, profile: str, png_bytes: bytes, filename: str) -> str:
    """Upload PNG to CMS /files. Returns file UUID."""
    cms = channels.get("cms", {})
    provider = cms.get("provider", "directus")
    base_url = cms.get("base_url", "").rstrip("/")
    token = read_secret(plugin_root, profile, cms.get("token_file", ".cms-token"))

    host = base_url.split("://")[-1].split("/")[0]
    if not dns_preflight(host):
        sys.exit("[publish] DNS preflight failed for CMS host")

    if provider == "directus":
        url = f"{base_url}/files"
        files = {"file": (filename, png_bytes, "image/png")}
        headers = {"Authorization": f"Bearer {token}"}
        resp = requests_with_retry("POST", url, files=files, headers=headers, timeout=60)
        if resp.status_code not in (200, 201):
            sys.exit(f"[publish] thumbnail upload failed {resp.status_code}: {resp.text[:300]}")
        data = resp.json().get("data", {})
        return data.get("id")
    else:
        sys.exit(f"[publish] CMS provider {provider} not implemented yet")


def build_post_payload(channels: dict, brand: dict, html: str, slug: str, thumbnail_id: str) -> dict:
    """Build CMS post payload using field mapping from channels.json."""
    cms = channels.get("cms", {})
    fields = cms.get("fields", {})
    title = extract_h1(html) or extract_title(html)
    description = extract_meta(html, "description") or extract_first_paragraph(html)[:200]
    author = extract_meta(html, "author") or brand.get("voice", {}).get("accounts", {}).get("company", {}).get("author_name") or brand.get("company", {}).get("name")
    keywords = extract_meta(html, "keywords")

    body_html = inline_css_into_body(html)

    payload = {}
    payload[fields.get("slug", "slug")] = slug
    payload[fields.get("title", "title")] = title
    payload[fields.get("description", "description")] = description
    payload[fields.get("body_html", "body_html")] = body_html
    if thumbnail_id:
        payload[fields.get("thumbnail", "thumbnail")] = thumbnail_id
    if keywords:
        payload[fields.get("keywords", "keywords")] = keywords
    if author:
        payload[fields.get("author", "author")] = author
    payload[fields.get("status", "status")] = cms.get("default_status", "published")
    payload[fields.get("published_at", "published_at")] = datetime.now(timezone.utc).isoformat()
    return payload


def post_blog(channels: dict, plugin_root: Path, profile: str, payload: dict) -> dict:
    cms = channels.get("cms", {})
    provider = cms.get("provider", "directus")
    base_url = cms.get("base_url", "").rstrip("/")
    token = read_secret(plugin_root, profile, cms.get("token_file", ".cms-token"))
    collection = cms.get("posts_collection", "posts")

    if provider == "directus":
        url = f"{base_url}/items/{collection}"
        headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
        resp = requests_with_retry("POST", url, json=payload, headers=headers, timeout=60)
        if resp.status_code not in (200, 201):
            sys.exit(f"[publish] post failed {resp.status_code}: {resp.text[:500]}")
        return resp.json().get("data", {})
    else:
        sys.exit(f"[publish] CMS provider {provider} not implemented yet")


# ============================================================
# Notifications
# ============================================================

def notify_telegram(channels: dict, plugin_root: Path, profile: str, message: str) -> None:
    notif = channels.get("notifications", {}).get("telegram", {})
    if not notif.get("enabled", False):
        return
    try:
        config_file = notif.get("config_file", ".notify-config")
        raw = read_secret(plugin_root, profile, config_file)
        cfg = json.loads(raw)
        bot_token = cfg.get("bot_token")
        chat_id = cfg.get("chat_id")
        if not bot_token or not chat_id:
            return
        url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
        import requests
        requests.post(url, json={"chat_id": chat_id, "text": message, "parse_mode": "Markdown"}, timeout=10)
    except Exception as e:
        print(f"[notify] telegram failed: {e}", flush=True)


# ============================================================
# Main
# ============================================================

def main():
    parser = argparse.ArgumentParser(description="Publish blog draft to CMS (generic, config-driven)")
    parser.add_argument("--slot", choices=["A", "B", "C"], help="Slot label - finds today's draft for this slot")
    parser.add_argument("--draft", help="Explicit draft path (overrides --slot)")
    parser.add_argument("--profile", help="Use examples/<profile>/config/ instead of config/")
    parser.add_argument("--date", help="Target date YYYY-MM-DD (default today, only with --slot)")
    parser.add_argument("--dry-run", action="store_true", help="Validate + render but do not POST to CMS")
    args = parser.parse_args()

    if not args.slot and not args.draft:
        parser.error("--slot or --draft required")

    plugin_root = find_plugin_root()
    brand = load_brand_config(plugin_root, args.profile)
    channels = load_channels_config(plugin_root, args.profile)

    # Resolve draft
    if args.draft:
        draft_path = Path(args.draft)
        if not draft_path.is_absolute():
            draft_path = plugin_root / args.draft
    else:
        draft_path = find_draft_for_slot(drafts_dir(plugin_root, args.profile), args.slot, args.date)

    if not draft_path.exists():
        sys.exit(f"Draft not found: {draft_path}")

    print(f"[publish] draft: {draft_path.name}", flush=True)
    html = draft_path.read_text(encoding="utf-8")
    slug = extract_slug_from_draft(draft_path)

    # Validate HTML
    ok, errors = validate_body_html(html, brand)
    if not ok:
        msg = f"[publish] VALIDATION FAILED for {draft_path.name}:\n  - " + "\n  - ".join(errors)
        print(msg, flush=True)
        notify_telegram(channels, plugin_root, args.profile,
                        f"*Blog publish failed* (validation)\n`{draft_path.name}`\n\n" + "\n".join(f"- {e}" for e in errors))
        sys.exit(1)
    print(f"[publish] validation: ok", flush=True)

    # Pick best figure + render thumbnail
    figures = extract_figures(html)
    idx, best_svg, best_score = pick_best_figure(figures)
    thumbnail_id = None
    if best_svg:
        print(f"[publish] picked figure {idx+1}/{len(figures)} (score={best_score:.1f}) for thumbnail", flush=True)
        png = render_svg_to_png(best_svg, width=1200)
        if args.dry_run:
            preview = drafts_dir(plugin_root, args.profile) / f"_preview-{slug}.png"
            preview.write_bytes(png)
            print(f"[publish] dry-run: wrote preview to {preview}", flush=True)
        elif channels.get("cms", {}).get("provider") == "none":
            # No CMS: stash the thumbnail next to the local HTML output.
            ready = outputs_root(plugin_root, args.profile) / "blogs" / "ready"
            ready.mkdir(parents=True, exist_ok=True)
            (ready / f"{slug}.png").write_bytes(png)
            print(f"[publish] no-CMS: thumbnail saved to {ready / (slug + '.png')}", flush=True)
        else:
            thumbnail_id = upload_thumbnail(channels, plugin_root, args.profile, png, f"{slug}.png")
            print(f"[publish] thumbnail uploaded: {thumbnail_id}", flush=True)
    else:
        print("[publish] no SVG figures found - publishing without thumbnail", flush=True)

    # Build + POST payload
    payload = build_post_payload(channels, brand, html, slug, thumbnail_id)

    if args.dry_run:
        print(f"[publish] dry-run: payload fields = {list(payload.keys())}", flush=True)
        return

    provider = channels.get("cms", {}).get("provider")
    if provider == "none":
        # No CMS: write the final inlined HTML for manual / GitHub publishing. Nothing is posted.
        ready = outputs_root(plugin_root, args.profile) / "blogs" / "ready"
        ready.mkdir(parents=True, exist_ok=True)
        body_html = inline_css_into_body(html)
        out_file = ready / f"{slug}.html"
        out_file.write_text(body_html, encoding="utf-8")
        print(f"[publish] no-CMS: wrote {out_file} (commit to GitHub or upload manually)", flush=True)
        post_id = slug
        posted = {"id": slug, "_local_path": str(out_file)}
    else:
        posted = post_blog(channels, plugin_root, args.profile, payload)
        post_id = posted.get("id") or posted.get(channels.get("cms", {}).get("fields", {}).get("slug", "slug"))
        print(f"[publish] posted: id={post_id}", flush=True)

    # Move draft to published archive
    archive = drafts_dir(plugin_root, args.profile) / f"published-{datetime.now().strftime('%Y%m%d')}-{slug}.html"
    draft_path.rename(archive)
    print(f"[publish] archived to {archive.name}", flush=True)

    # Public URL pattern from channels.json
    cms = channels.get("cms", {})
    public_url = cms.get("public_url_pattern", "").replace("{slug}", slug)

    notify_telegram(channels, plugin_root, args.profile,
                    f"*Blog published*\n`{slug}`\n{public_url}\n\nFigure {idx+1}/{len(figures)} as thumbnail.")


if __name__ == "__main__":
    main()
